/**
 * Turns the brand mark into the constant the invoice renderer draws.
 *
 *     packages/tax/assets/hitbox-logo.svg                  ← source of truth (vector)
 *     packages/tax/assets/hitbox-logo.png                  ← GENERATED raster
 *     packages/tax/src/infrastructure/hitbox-logo.asset.ts ← GENERATED, what ships
 *
 * Run it whenever the artwork changes:
 *
 *     pnpm --filter @hitbox/tax logo:generate
 *
 * Three things this script exists to handle, none of them optional:
 *
 *   **PDFKit cannot draw an SVG.** `doc.image()` accepts PNG and JPEG only, so
 *   the vector has to be rasterised somewhere. Doing it here, once, at build
 *   time, keeps the render path free of an image-conversion dependency and
 *   makes the exact pixels that go on an invoice reviewable in a diff.
 *
 *   **The raster has to be sized for print, not for screen.** The mark prints
 *   at ~40pt tall, which is 0.56 inch; at 600 dpi that is ~333 px. RASTER_PX is
 *   384, comfortably above it, so the cube's diagonals stay clean on paper.
 *
 *   **The bytes are embedded, not read from disk.** An invoice is a statutory
 *   document and must render identically wherever it is produced — the server
 *   (ESM), a test (CommonJS), a bundle with no assets directory beside it. A
 *   missing file must not be able to produce a logo-less invoice. It also keeps
 *   the renderer free of `import.meta.url`, which does not exist under the
 *   CommonJS transform the test suite compiles to.
 *
 * The base64 is emitted as 96-character single-quoted chunks rather than one
 * enormous line, so the file is legible and a re-generation produces a readable
 * diff instead of one unreviewable 20 KB line.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SVG_PATH = resolve(ROOT, 'assets/hitbox-logo.svg');
const PNG_PATH = resolve(ROOT, 'assets/hitbox-logo.png');
const TS_PATH = resolve(ROOT, 'src/infrastructure/hitbox-logo.asset.ts');

/** Width in pixels of the generated raster. See the note above. */
const RASTER_PX = 384;
/** Characters per line in the emitted base64. */
const CHUNK = 96;

const HEADER = `/**
 * The HitBox mark printed on every invoice, embedded as base64.
 *
 * GENERATED by packages/tax/scripts/generate-logo.ts from
 * packages/tax/assets/hitbox-logo.svg — edit the SVG and re-run
 * \`pnpm --filter @hitbox/tax logo:generate\`, never this file.
 *
 * A PNG rather than the SVG because PDFKit's \`doc.image()\` accepts PNG and
 * JPEG only, rasterised at ${RASTER_PX}px for a mark that prints ~40pt tall
 * (~333px at 600dpi).
 *
 * Embedded rather than read from disk so the document is identical wherever it
 * is produced: the server (ESM), a test (CommonJS) and a bundle with no assets
 * directory beside it all get the same bytes. It also keeps the renderer free
 * of \`import.meta.url\`, which does not exist under the CommonJS transform the
 * test suite compiles to.
 *
 * A deployment can still point TAX_INVOICE_LOGO_PATH at a PNG on disk, which
 * overrides this.
 */
const BASE64 =
`;

async function main(): Promise<void> {
    const svg = readFileSync(SVG_PATH);

    // `density` is what makes a vector rasterise crisply: without it sharp
    // renders the SVG at its nominal 72dpi size and then upscales, which
    // softens every edge on the cube.
    const png = await sharp(svg, { density: 600 })
        .resize({ width: RASTER_PX })
        .png({ compressionLevel: 9 })
        .toBuffer();

    writeFileSync(PNG_PATH, png);

    const encoded = png.toString('base64');
    const lines: string[] = [];
    for (let index = 0; index < encoded.length; index += CHUNK) {
        lines.push(`    '${encoded.slice(index, index + CHUNK)}' +`);
    }
    const body = lines.join('\n').replace(/ \+$/, ';');

    writeFileSync(
        TS_PATH,
        `${HEADER}${body}\n\nexport const HITBOX_LOGO_PNG: Buffer = Buffer.from(BASE64, 'base64');\n`,
        'utf-8',
    );

    const meta = await sharp(png).metadata();
    // eslint-disable-next-line no-console
    console.log(`svg  ${SVG_PATH}  ${svg.length} bytes`);
    // eslint-disable-next-line no-console
    console.log(`png  ${PNG_PATH}  ${meta.width}x${meta.height}  ${png.length} bytes`);
    // eslint-disable-next-line no-console
    console.log(`ts   ${TS_PATH}  ${encoded.length} base64 chars, ${lines.length} lines`);
}

main().catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exit(1);
});
